(* * * * * * * * * * *
 * Resource Aware ML *
 * * * * * * * * * * *
 *
 * * *  Unit Tests * *
 *
 * File:
 *   tests/functions.ml
 *
 * Author:
 *   Jan Hoffmann, Shu-Chun Weng (2014)
 * 
 * Description:
 *   Simple function definitions.
 *   
 *)


let a = 4

let f : int -> int * int = fun x -> (a,x)

let id : int -> int = fun x -> x

let id2 : float -> float -> float * float = fun n m -> (n,m)

let fst : bool -> bool -> bool = fun a b -> a

let snd : bool -> bool -> bool = fun a -> fun b -> b

let snd : bool -> bool -> bool = fun a -> let x = 1 in fun b -> b

let _ = let x = 5 in 
        let y = 6 in (id x,y)

let _ = id2 1.0 2.0, fst true false


