(* * * * * * * * * * *
 * Resource Aware ML *
 * * * * * * * * * * *
 *
 * * *  Unit Tests * *
 *
 * File:
 *   tests/lets.ml
 *
 * Author:
 *   Jan Hoffmann, Shu-Chun Weng (2014)
 * 
 * Description:
 *   Nested let bindings.
 *   
 *)


let shoot = 4

let _ = 5

let x = let y = 1.0 in
        let z = let x = 9 in x in
	let x = 3 in
	let z = 3.0 in
	let z = let z = 4 in 1.1 in
	let z = z in
        4

let _ = let x = x in x


;; 9