(** 
 * [rev l] return the reversed l. 
 *)

let rev l = 
	let rec rev_aux l acc = 
  		match l with 
  		| [] -> let _ = Raml.tick(2.0) in acc
  	 	| h::t -> let _ = Raml.tick(4.0) in 
    		let x = h::acc in rev_aux t x
 	 in rev_aux l [] 

let rev_rev l = rev (rev l)
 